#!/usr/bin/env ruby
require 'pusher'
require 'pusher-client'
require 'msgpack'
require 'xz'
require 'ascii85'
require 'gibberish'
require 'securerandom'
require 'digest/md5'
require 'gli'
require 'eat'
require 'json'
require 'open3'

include GLI::App
program_desc 'The Ting Tings'
version 1.0


### compress
def msgpack(data,enc=:encode)
  return data.to_msgpack if enc == :encode
  MessagePack.unpack(data)
end

def xz(data,enc=:encode)
  return XZ::compress(data) if enc == :encode
  XZ::decompress(data)
end

def ascii85(data,enc=:encode)
  return Ascii85.encode(data) if enc == :encode
  Ascii85.decode(data)
end

### encrypt
def aes(data,enc=:encode)
  return @cipher.enc(data) if enc == :encode
  @cipher.dec(data)
end

def encode(data,redux=@config[:redux])
  redux.inject(data) do |enc,encoder|
    data = send(encoder.to_sym, data, :encode)
  end
  data
end

def decode(data,redux=@config[:redux])
  redux.reverse.inject(data) do |enc,encoder|
    data = send(encoder.to_sym, data, :decode)
  end
  data
end

### upnp
def upnp(pattern="ExternalIPAddress")
  stdin, stdout, stderr = Open3.popen3('upnpc -l')
  for line in stdout.readlines
    return line.split.last if line =~ /#{pattern}/
  end
end

def sshfp(type=:rsa)
  stdin, stdout, stderr = Open3.popen3("ssh-keygen -lf /etc/ssh/ssh_host_#{type.to_s}_key.pub")
  for line in stdout.readlines
    return line.split[1]
  end
end

### Global flags
desc 'Config'
default_value "#{File.basename(__FILE__)}.yml"
arg_name 'config'
flag [:config]

desc 'Secret Key'
default_value "#{File.basename(__FILE__)}.key"
arg_name 'key'
flag [:key]

desc 'Hosts directory'
default_value "#{File.dirname(__FILE__)}/hosts"
arg_name 'hosts'
flag [:hosts]

desc 'Privileged user'
default_value "sysop"
arg_name 'user'
flag [:user]

desc 'Timeout'
default_value 60
arg_name 'timeout'
flag [:timeout]

### Global switches
desc 'Use UPNP'
switch [:upnp]

desc 'Use SQL'
switch [:sql]

desc 'Monitor'
switch [:monitor]

desc 'Daemon'
switch [:daemon]

### Global variables
@prog="#{File.basename(__FILE__)}"

def msg(m="")
  puts "[#{@prog}] #{m}"
  STDOUT.flush
end

### Commands
desc 'Ting client'
arg_name ''
command :client do |cmd|
  cmd.action do |global_options,options,args|
    cfg   = @config[:pusher]

    PusherClient.logger = Logger.new(STDOUT)
    PusherClient.logger.level = Logger::INFO
    options = {:secret => cfg[:secret]} 
    socket = PusherClient::Socket.new(cfg[:key], options)

    # Subscribe to two channels
    socket.subscribe(cfg[:channel])
    socket[cfg[:channel]].bind(cfg[:event]) do |data|
      begin
        cmd, data = decode(data)

        case cmd
        when 'ping'
          # in monitor mode we dont ping
          next if global_options[:monitor]

          # pong
          chan  = cfg[:channel]
          event = cfg[:event]
          ip = global_options[:upnp] ? upnp() : eat('http://ifconfig.me/ip', :timeout => global_options[:timeout] )
          pong = {
            :id => @config[:myid],
            :ip => ip.strip,
            :fp_rsa => sshfp(),
            :fp_dsa => sshfp(:dsa),
            :fp_ecdsa => sshfp(:ecdsa)
          }
          Pusher[chan].trigger(event, encode(['pong',pong]))
        when 'pong'
          data.tap do |h|
            h.keys.each { |k| h[k.to_sym] = h.delete(k) }
          end
          out = "#{global_options[:hosts]}/#{data[:id]}.json"
          File.open(out,"w") do |f|
            f.write(JSON.pretty_generate(data))
          end
          msg( data )
        end # case cmd

      rescue Exception => e
        msg "socket bind Exception: #{e.message}"
        sleep 3
        # retry
      end

    end # socket do data

    socket.connect

  end
end

desc 'Ping'
arg_name ''
command :ping do |cmd|
  cmd.action do |global_options,options,args|
    cfg   = @config[:pusher]
    chan  = cfg[:channel]
    event = cfg[:event]
    Pusher[chan].trigger(event, encode(['ping',args]))
  end
end

desc 'Generate shared key'
arg_name ''
command :genkey do |cmd|
  cmd.action do |global_options,options,args|
    print SecureRandom.urlsafe_base64(len=32)
  end
end

pre do |global,command,options,args|

  # change to base directory
  Dir.chdir(File.dirname(__FILE__))

  @config = YAML.load( ERB.new( File.read( global[:config] ) ).result )
  @config[:id] = global[:id] || command.name.to_s
  {:args=> args, :global=> global, :options=> options}.each { |k,v| @config[k] = v }
  @config[:key] = File.read( global[:key] )
  @cipher = Gibberish::AES.new(@config[:key])
  msg "Configuration loaded: #{global[:config]}"

  # init Pusher
  cfg = @config[:pusher]
  Pusher.app_id = cfg[:app_id]
  Pusher.key    = cfg[:key]
  Pusher.secret = cfg[:secret]
  # Pusher.encrypted =
  msg "Pusher initialized: #{cfg[:app_id]}"

  # UPNP discovery
  if global[:u]
    @externalip = upnp()
    die('UPNP failed') if @externalip.empty?
    msg "External UPNP IP: #{@externalip}"
  end

  # init hosts
  Dir.mkdir(global[:hosts]) unless File.exists?(global[:hosts])

  msg "Ting ready"
  true
end

post do |global,command,options,args|
  true
end

on_error do |exception|
  STDERR.puts exception.backtrace
  # require 'pry'
  # binding.pry
  true
end

exit run(ARGV)
